### ISSUE TITLE
Create event page

### ISSUE THREAD

**Issue by marcoT89** [marcoT89/safira#1]
As a user,
I want to create an event
so that I can organize my events better.

**Acceptance Criteria:**
 - I want to see a link to publish my events on my social media.

**Tasks:**
- [ ] Create the API
- [ ] Create the event form page
- [ ] Create the event view page (accessed by public link)
